### ISSUE TITLE
GitHub Actions run in infinite loop

### ISSUE THREAD

**Issue by ReagentX** [ReagentX/Logria#36]
Using the following configuration:

```yml
name: Test

on:
  pull_request:
    branches:
        - main
        - develop

env:
  CARGO_TERM_COLOR: always

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Lint
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
```

GitHub Actions do not work. They run infinitely on tests that access the file system, which is most of them.

https://github.com/ReagentX/Logria/runs/2205703953?check_suite_focus=true
